### ISSUE TITLE
Download satellite data only when necessary

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#12]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

Should only download satellite data from Amazon S3, only when it has not already been downloaded.

## Developer Notes

- Should create a method that checks for local. 
`def check_local(s3_bucket, s3_key, local_directory) => Boolean`
- If #10 or #9 are done, add this check to them

## Known Blockers

- None

## Sub-Tasks

- None

## Acceptance Criteria

- [x] Tested
- [x] If #10 or #9 are done, this check is added to them

**Comment by camenpihor** [comment]
can use _check_local() method in PR #47

**Comment by Ferrumofomega** [comment]
Then this is done, right?

**Comment by camenpihor** [comment]
Not yet! I think we should add this check to the batch downloading and the downloading a single file. I think this issue is mostly copy and pasting, but I was thinking of doing it after the issue #10 is done.

**Comment by camenpihor** [comment]
Done!
