### ISSUE TITLE
Document the NAS Structure

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#30]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

The NAS compute cluster has a complex structure (PFEs, SFEs, LFEs, etc.), we should document this for ourselves. 

## Developer Notes

- Google doc, readme, other markdown file?
- Do we want this to be connected to this repository, if so how?

## Known Blockers

- None

## Sub-Tasks

- None

## Acceptance Criteria

- [ ] completed

**Comment by Ferrumofomega** [comment]
Created start here: [https://github.com/joyprojects/wildfire/tree/ssh-config-example](url)
