### ISSUE TITLE
Script job creation in the NAS HPC

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#31]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

We will probably be submitting a lot of jobs to the NAS compute cluster, so we should just script this using PBS files.

## Developer Notes

- None

## Known Blockers

- None

## Sub-Tasks

- None

## Acceptance Criteria

- [x] works

**Comment by Ferrumofomega** [comment]
Added sample pbs file here [https://github.com/joyprojects/wildfire/tree/ssh-config-example](url)

**Comment by camenpihor** [comment]
@Ferrumofomega and I talked about this and we think its really possible! The goals are to be able to reserve a node or start a job or a jupyter lab server from PFE

**Comment by camenpihor** [comment]
@Ferrumofomega noticed that whenever one reserved a node that the node id is always the same, we can use this to ease our scripting
