### ISSUE TITLE
Create documentation for SSH

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#32]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

MANDATORY

## Developer Notes

- OPTIONAL

## Known Blockers

- OPTIONAL

## Sub-Tasks

- [x] OPTIONAL

## Acceptance Criteria

- [x] MANDATORY

**Comment by Ferrumofomega** [comment]
Got a start here: [https://github.com/joyprojects/wildfire/tree/ssh-config-example](url)
