### ISSUE TITLE
Update satellite downloading code to work on the HPC

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#35]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

Make satellite data downloading work on the HPC and retain its ability to work locally.

## Developer Notes

- Just make the code work, nothing else

## Known Blockers

- #9
- #10 

## Sub-Tasks

- None

## Acceptance Criteria

- [x] code runs both locally and on HPC

**Comment by Ferrumofomega** [comment]
@camenpihor I'm working on this with the `dask-test` branch live on NAS, :-).
